apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-odoo-pv
  namespace: odoo-app
spec:
  capacity:
    storage: 120Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: files-storageclass
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: "/odoo-dev"
    server: "10.6.128.10"
