apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-odoo-pvc
  namespace: odoo-app
spec:
  storageClassName: files-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 120Gi

