apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config-file
data:
  odoo.conf: |
    [options]
    addons_path = /mnt/enterprise,/mnt/PortnetV14
    data_dir = /var/lib/odoo
    admin_passwd = damansoft@2021
    db_host = 10.50.128.110
    db_port = 31363
    #db_name = odoo
    #    db_user = odoo
    #        db_password = odoo
    #            max_cron_threads = 1
